#!/bin/bash

m -fr htmlcov
coverage run --branch --source=python_perl_storable -m pytest tests/ && \
	coverage report -m && coverage html && \
    if [ "$1" == "open" ]; then xdg-open htmlcov/index.html; fi
