#!/bin/sh

echo
echo step 1
python3 -m pip install --user --upgrade setuptools wheel

echo
echo step 2
python3 setup.py sdist bdist_wheel

echo
echo step 3
python3 -m pip install --user --upgrade twine

echo
echo step 4
python3 -m twine upload --repository testpypi dist/*

echo
echo step 5
# Поменять название!
python3 -m pip install --index-url https://test.pypi.org/simple/ --no-deps python-perl-storable

echo
echo step 6
# Поменять название!
pip3 uninstall python_perl_storable

echo
echo step 7
twine upload dist/*
